FROM python:3.11-slim

WORKDIR /app

COPY requirements-prod.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements-prod.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app/streamlit/app.py", "--server.address=0.0.0.0", "--server.port=8501"]